version: "3"
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: laravel
    working_dir: /app
    volumes:
      - ./src:/app

  web:
    image: nginx
    container_name: web
    depends_on:
      - laravel
    environment:
      - NGINX_MAX_BODY=100M
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8000:80
    volumes:
      - ./src:/app
      - ./docker/default.template:/etc/nginx/conf.d/default.template

  redis:
    container_name: redis
    image: "redis:alpine"

  beanstalk:
    container_name: beanstalk
    image: "jonbaldie/beanstalkd"

  queue:
    image: vivifyideas/php-fpm-production-docker-alpine
    container_name: queue
    working_dir: /app
    command: 'php artisan queue:listen --tries=3 --timeout=60'
    volumes:
      - ./src:/app

  db:
    image: mariadb:10.2
    container_name: db
    environment:
      MYSQL_DATABASE: laravel-boilerplate
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  mailhog:
    image: "mailhog/mailhog"
    ports:
      - 8025:8025

volumes:
  db:

